input {
  beats {
    port => 5044
  }
}
filter {
  json {
    source => "message"
    target => "docker"
    skip_on_invalid_json => true
  }
  mutate {
    add_field => { "service" => "%{[docker][container][name]}" }
  }
}
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logvigil-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
